apiVersion: v1
kind: Service
metadata:
  name: zabbix-service
  namespace: default
spec:
  selector:
    app: zabbix
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: web
  - protocol: TCP
    port: 80
    targetPort: 80
    name: sample-app
  - protocol: TCP
    port: 10050
    targetPort: 10050
    name: zabbix-server-0
  - protocol: TCP
    port: 10051
    targetPort: 10051
    name: zabbix-server-1
  externalIPs: ['54.168.45.70']
