apiVersion: v1
kind: Service
metadata:
  name: monitoring
  namespace: default
spec:
  selector:
    app: monitoring-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: zabbix-app
  namespace: default
  labels:
    app: monitoring-test
spec:
  containers:
  - name: httpd
    image: httpd:2.4
    ports:
    - containerPort:  80
  - name: zabbix-agent
    image:  zabbix/zabbix-agent:alpine-5.4-latest
    env:
    - name: ZBX_SERVER_HOST
      value: 172.31.40.27
    - name: ZBX_HOSTNAME
      value: worker1